### PR TITLE
vulnerable: upgrade debug dependency

### PR DESCRIPTION
**Pull request by flecno**
your current release uses vulnerable dependencies. There is a [vulnerable reported](https://nodesecurity.io/advisories/46) for ms (dependency from debug).

Because your master doesn't build for now I forked from your current v0.7.2 tag. Can you update the debug dependeny and release a new version please! :)

My project will not build if there are open vulnerables detected by [nsp](https://github.com/nodesecurity/nsp)

### CODE REVIEW

**Comment by flecno** [comment]
Mhm. iojs fails.. I used locally node 0.12 which builds and the tests pass. Node v4 fails too. I think that's a known problem which breaks your master too? Can you accept the PR anyway?

**Comment by sonnyp** [comment]
@flecno thanks

node > 0.12 is not supported (yet?)
https://github.com/node-xmpp/node-stringprep/pull/72

**Comment by flecno** [comment]
thanks for merging... Can you publish a new version? So I can request updates for the libraries I use?

**Comment by sonnyp** [comment]
done, v0.7.3

**Comment by sonnyp** [comment]
@flecno thanks for your effort!

**Comment by sonnyp** [comment]
@flecno thanks for making Node.js platform more secure!

**Comment by flecno** [comment]
thank you :+1:

**Pull request merged**
